### PR TITLE
fix: correcting try catch in php

### PR DESCRIPTION
**Pull request by IgorDePaula**
correcting try catch in php

### CODE REVIEW

**Review by roxblnfk — COMMENTED** [review]
Current syntax is correct since PHP 8.0
https://wiki.php.net/rfc/non-capturing_catches

**Comment by rustatian** [comment]
Thanks, @roxblnfk. Since syntax in docs is correct, thank you for the PR @IgorDePaula , but I have to decline it.

**Comment by IgorDePaula** [comment]
If I want run php 7.x? I make this PR because I run it with php 7.4.
@rustatian @roxblnfk

**Comment by roxblnfk** [comment]
> I make this PR because I run it with php 7.4.

Good reason for PR.

But PHP 7.4 is [almost dead](https://www.php.net/supported-versions.php). And this is good reason for declining for the PR.

**Pull request closed without merging**
