### PR TITLE
Update section metrics 

### PR DESCRIPTION
**Pull request by Smolevich**
- Add info about middleware `http_metrics` in metrics section

### CODE REVIEW

**Comment by rustatian** [comment]
@Smolevich Hey 👋🏻 
We need to show all available metrics, including temporal, jobs, grpc, and tcp.

**Comment by Smolevich** [comment]
@rustatian What should i change?

**Comment by rustatian** [comment]
@Smolevich 
It would be nice to add all available metrics. When you start RR with `jobs`, `temporal`, `grpc` plugins enabled, you'll see all available metrics in the Prometheus. 

That'd be great to have sections like `temporal`, `grpc` etc, and a list of associated metrics separated with a newline. For the temporal, you may add these links: https://docs.temporal.io/references/sdk-metrics, https://docs.temporal.io/operation/how-to-tune-workers/#metrics

**Comment by rustatian** [comment]
@Smolevich Friendly ping 😃 Are you planning to finish this PR?

**Comment by Smolevich** [comment]
@rustatian yes, i want to finish in next week :smile

**Pull request closed without merging**
