### PR TITLE
Update cache documentation

### PR DESCRIPTION
**Pull request by darkweak**
Need to wait for a fix on the velox repository because nested repository are not supported. 
I think we could set `repository= "/repo_name/folder/sub"` and split on the first `/` and build the github api call with `https://api.github.com/repositories/{repo_id already calculated from velox}/contents/{second part of the repository property}` (e.g. `repository` contains `/repo_name/folder/sub` `https://api.github.com/repositories/1234567/contents/folder/sub`).

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @darkweak 👋🏻 
I don't think that we'll support the nested repos. A plugin is supposed to be at the root of the repository, and there are no limits on the folders/nestedness for the plugin repo until the `struct Plugin` is located at the root of the repo.

**Comment by darkweak** [comment]
Hey @rustatian ✌️  
In this case we have to clone first the repository and after that use the replace directive because each souin plugins are in a folder. That could be a pain for users to do that each time they want to use the cache.
Or we could do something like Træfik with a config file located at the root repository (e.g. https://github.com/darkweak/souin/blob/master/.traefik.yml)? WDYT about that?

**Comment by rustatian** [comment]
I previously thought about configuration at the root or the plugin's repo, but it seems to be an unnecessary overcomplication...

We may introduce an additional option to the `velox.toml` configuration -> `folder = souin/roadrunner`. Then we won't need a complicated parser and the user will be able to set the folder explicitly. We only need to give a good name to this option.
My proposals are `folder=`, `origin_folder=` (might be toooooo long). wdyt?

**Comment by darkweak** [comment]
I stand for the `folder=`, it's a pretty clear option 👍

**Comment by rustatian** [comment]
Sold 😄 
I'm busy with the `beta.3` release atm... I'll implement this on the weekend if you don't mind.

**Pull request merged**
