### PR TITLE
Add new docker image

### PR DESCRIPTION
**Pull request by roquie**

### CODE REVIEW

**Review by rustatian — APPROVED** [review]
lgtm

**Comment by rustatian** [comment]
Thanks @roquie

**Comment by jjsaunier** [comment]
Should we use this image as replacement instead of `COPY --from=spiralscout/roadrunner:2.3.3 /usr/bin/rr /usr/bin/rr` for example ?

**Comment by rustatian** [comment]
> Should we use this image as replacement instead of `COPY --from=spiralscout/roadrunner:2.3.3 /usr/bin/rr /usr/bin/rr` for example ?

As you wish :) 
Official image is what's in your message. `COPY --from=spiralscout/roadrunner:2.3.3`. Images in this PR are community images.

**Pull request merged**
